# Generated by Django 2.2.1 on 2019-06-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costomer',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='costomer_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='costomer',
            new_name='customer',
        ),
    ]
